services:
  - type: web
    name: tattersalls-api
    env: python
    runtime: python3.10
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      echo "=== Checking uvicorn path & version ==="
      which uvicorn || echo "uvicorn not found in PATH"
      python -m uvicorn --version || echo "python -m uvicorn failed"
    startCommand: python -c "import os; from uvicorn import run; run('main:app', host='0.0.0.0', port=int(os.environ['PORT']))"
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: CA_CERT_PATH
        value: "./ca-certificate.crt"
